#!/usr/bin/expect

set timeout -1;
set user [lindex $argv 0];
set pass [lindex $argv 1];
set newpass [lindex $argv 2];
spawn ssh netsec.cs.northwestern.edu -l $user;
match_max 100000;
expect *password:*;
exp_send -- $pass\r;
expect {
    -re ".*@netsec.*\$" {
	puts "logged in!";
	exp_send passwd\r;
	expect -re ".*current.*password:";
	puts "correct"
	exp_send $pass\r;
	expect -re ".*Enter.*password:";
	puts correct
	exp_send $newpass\r;
	expect -re ".*Retype.*password:";
	puts correct
	exp_send $newpass\r;
	expect -re ".*success.*";
    }
    -re ".*denied.*" {
	puts "denied";
	exit 1
    }
}
#



